### ISSUE TITLE
Map result to POCO of different type to Entity

### ISSUE THREAD

**Issue by MarkioE** [SqlRepo/sqlrepo#6]
We currently have the ability to write queries that return counts, joins, reduced data etc. It would be useful to map these to a POCO which is a different type to the Entity we are querying against.

One case:
`var downloadsByDayQuery = repository.Query()
                .CountAll()
                .WhereBetween(e => e.Timestamp, _from, _to)
                .GroupBy(e => e.TimestampDay)`

I want to return this to a simple POCO that looks like
`public class DownloadByDayQueryResult
{
    public int Count { get; set; }
    public DateTime Day { get; set; }
}`

This could be done in the Go method, but only for SelectCommand.
` .Go<DownloadByDayQueryResult>(_connectionString)`

Any thoughts for this?

**Comment by testpossessed** [comment]
I am pretty sure you can already do this, but overriding the table name in the query.  CountAll is meant to be a column selection rather than returning a value.

The entity of the repository is only significant when the table name is not overridden.

What I am not sure about is what the column name in the datareader would be if you don’t/can’t specify it in CountAll.

As long as the shape of the result set from the query matches the entity you should be able to use anything as long as you override the table name.

If we do anything like this I would rather we do it higher up.  So something like

repositoryFactory.Create<TypeToQuery, TypeToReturn>(…);

And the current implementation would effectively delegate to this method with the same type for both arguments.

**Comment by testpossessed** [comment]
Is it ok to close this one?

**Comment by MarkioE** [comment]
Yes I will close.
